### PR TITLE
Use blkid when Disk By-PartTypeUUID unavailable 

### PR DESCRIPTION
**Pull request by brwyatt**
This patch falls back to parsing output from `blkid` if
/dev/disk/by-parttypeuuid doesn't exist (such as is the case on Ubuntu
16.04 "Xenial" and CentOS 7)

Without this fix, systems without parttypeuuid will fail subsequent runs after Ceph OSD is configured.

### CODE REVIEW

**Comment by jordanconway** [comment]
@brwyatt 4704db9 Seems to break on CentOS 7 as lsblk with the parttype field is only in util-linux >= 2.25 and CentOS 7.2 currently only has version 2.23.2

**Comment by brwyatt** [comment]
@mricon @jordanconway Nice catch!

I'm going to try and spend some time to get this taken care of, shouldn't be too difficult.

**Comment by brwyatt** [comment]
@mricon @jordanconway Let me know if the latest commit works for y'all!

**Comment by jordanconway** [comment]
@brwyatt It looks good for this change - although there seem to be some issues with the prerequisite for redhat-lsb-core. You're trying to access $::lsbmajdistrelease in params.pp but it's provided by Package redhat-lsb-core which is only installed in install.pp
It works perfectly if  redhat-lsb-core is already installed though.

**Comment by brwyatt** [comment]
@jordanconway Glad it worked!

As to the $::lsbmajdistrelease, though... unfortunately, that's not something I've added, as it was part of the module before I started using it. A lot of modules use that fact, so it might be good to have redhat-lsb-core installed in base images. However I think there are also some alternate facts as well, so I might be able to put in another PR to change to one of those, but it would be pretty low on my priority list (most systems I work with have the LSB packages installed by default), but the change should be trivial.

**Comment by jordanconway** [comment]
@brwyatt I didn't see it in the datacenterd params.pp https://github.com/datacentred/puppet-ceph/blob/master/manifests/params.pp so I thought it was something in one of your PRs.
The issue isn't that it's being used, it's that it's being used before install.pp is called to install it.

**Comment by brwyatt** [comment]
@jordanconway You're right, my mistake! I forgot about that one, it is part of PR #4.

I'll comment over there about this.

**Comment by brwyatt** [comment]
I believe commit 66787901 resolves the original issue by switching to `sgdisk`.

**Pull request closed without merging**
