### PR TITLE
Add compatability for Jewel and systemd

### PR DESCRIPTION
**Pull request by brwyatt**
Heavily based on @nerdmagic's Pull Request #3 on datacentred/puppet-ceph, but generalized to support Ubuntu Xenial, which also uses systemd.

Tested across three Xenial nodes built in Vagrant using this manifest:

``` puppet
node /ceph\d/ {

  Exec {
    path => '/bin:/usr/bin:/sbin:/usr/sbin',
  }

  package { 'ntp':
    ensure => installed,
  }

  class { 'ceph':
    mon   => true,
    osd   => true,
    conf  => {
      'global' => {
        'fsid'                      => '62ed9bd6-adf4-11e4-8fb5-3c970ebb2b86',
        'mon_initial_members'       => 'ceph0',
        'mon_host'                  => '10.10.1.10,10.10.1.11,10.10.1.12',
        'public_network'            => '10.10.1.0/24',
        'cluster_network'           => '10.10.1.0/24',
        'auth_supported'            => 'cephx',
        'filestore_xattr_use_omap'  => true,
        'osd_crush_chooseleaf_type' => 0,
      },  
      'osd'    => {
        'osd_journal_size' => '512',
      },  
    },  
    disks => {
      '3:0:0:0/3:0:0:0' => {}, 
      '4:0:0:0/4:0:0:0' => {}, 
    },  
  }
}
```

### CODE REVIEW

**Comment by nerdmagic** [comment]
Awesome, thanks for fixing Ubuntu as well!

**Comment by brwyatt** [comment]
From @jordanconway in #10 : "You're trying to access $::lsbmajdistrelease in params.pp but it's provided by Package redhat-lsb-core which is only installed in install.pp
It works perfectly if redhat-lsb-core is already installed though."

Can you confirm that $::operatingsystemmajrelease is present through facter on your systems without lsb? If so, I could probably switch it to use that instead if that fact is present without the lsb packages installed.

I do use $::lsbdistcodename as well, but only within the Ubuntu-specific sections, which should have lsb installed out of the box, so that shouldn't be an issue.

**Comment by jordanconway** [comment]
@brwyatt yes $::operatingsystemmajrelease works on CentOS7 (Puppet4) without any lsb packages installed. However is it not on my CentOS 6 systems (puppet2.7) so that may complicate things.

**Comment by brwyatt** [comment]
@jordanconway Okay. I think I can fix it for the CentOS7 by switching this to use $::operatingsystemmajrelease instead. I don't think there's any alternative I can do for this module to make it work for the ones running Puppet 2.7, though.

What I can offer, however, is a potential workaround with a custom Factor fact. An older version of stahnma/epel has a custom fact to populate the $::operatingsystemmajrelease fact: https://github.com/stahnma/puppet-module-epel/blob/0.1.0/lib/facter/os_maj_version.rb

This won't override the fact if it already exists (since it comes from Factor directly in the versions that have that fact), but will populate it if it isn't set.

**Comment by jordanconway** [comment]
@brwyatt I won't be using this on CentOS6 or puppet 2.7, it's just the EL6 box I had available to check. Thanks for the heads up though!

**Comment by brwyatt** [comment]
@jordanconway Sounds good! I'll check into switching that variable when I have a spare sec to look at it.

**Comment by brwyatt** [comment]
I believe this has been resolved with commit 66787901 in master.

**Pull request closed without merging**
